using System;
using System.Collections.Generic;
using System.Data;

namespace AutoMappic;

/// <summary>
///   Provides highly optimized mapped enumerations natively over <see cref="IDataReader"/>.
/// </summary>
public static class DataReaderExtensions
{
    /// <summary>
    ///   Maps a data reader's output straight to an enumerable of strongly-typed objects based on matching column names
    ///   or configured rules. Highly optimized and zero-reflection, directly generated by the AutoMappic interceptor.
    /// </summary>
    /// <typeparam name="TDestination">The target model to bind to.</typeparam>
    /// <param name="reader">The native ADO.NET data reader to project.</param>
    /// <returns>A deferred sequence of instances bound from the reader.</returns>
    /// <exception cref="AutoMappicException">Thrown if executed natively outside the source generator.</exception>
    public static IEnumerable<TDestination> Map<TDestination>(this IDataReader reader)
    {
        throw new AutoMappicException("IDataReader.Map<TDestination>() must be intercepted by the AutoMappic source generator.");
    }

    /// <summary>
    ///   Asynchronously maps a database reader's output straight to a list of strongly-typed objects using ReadAsync.
    ///   Highly optimized and zero-reflection, directly generated by the AutoMappic interceptor.
    /// </summary>
    /// <typeparam name="TDestination">The target model to bind to.</typeparam>
    /// <param name="reader">The native DbDataReader to project.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>An asynchronous sequence of strongly-typed instances bound from the reader.</returns>
    /// <exception cref="AutoMappicException">Thrown if executed natively outside the source generator.</exception>
    public static global::System.Collections.Generic.IAsyncEnumerable<TDestination> MapAsync<TDestination>(this global::System.Data.Common.DbDataReader reader, global::System.Threading.CancellationToken cancellationToken = default)
    {
        throw new AutoMappicException("DbDataReader.MapAsync<TDestination>() must be intercepted by the AutoMappic source generator.");
    }
}
