// <auto-generated/>
#nullable enable
namespace AutoMappic.Generated
{
    /// <summary>Provides runtime state for recursive graph mapping and identity management.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public readonly struct MappingContext
    {
        private readonly global::System.Collections.Generic.Dictionary<global::System.ValueTuple<global::System.Type, object>, object>? _tracked;
        
        /// <summary>The current recursion depth.</summary>
        public int Depth { get; }

        /// <summary>Initializes a new context without tracking.</summary>
        public MappingContext() { _tracked = null; Depth = 0; }
        
        /// <summary>Initializes a context and creates tracking buffers if enabled.</summary>
        public MappingContext(bool enableTracking) { _tracked = enableTracking ? new() : null; Depth = 0; }
        
        private MappingContext(global::System.Collections.Generic.Dictionary<global::System.ValueTuple<global::System.Type, object>, object>? tracked, int depth)
        {
            _tracked = tracked;
            Depth = depth;
        }

        /// <summary>Increments the recursion depth and returns a new context state.</summary>
        public MappingContext Next()
        {
            if (Depth > 128) throw new global::AutoMappic.AutoMappicException("Circular mapping detected (Max depth 128 exceeded). Enable Identity Management on your mapping profile to handle circular graphs.");
            return new MappingContext(_tracked, Depth + 1);
        }

        /// <summary>Attempts to retrieve a tracked entity reference.</summary>
        public bool TryGetEntity<TEntity>(object key, out TEntity entity) where TEntity : class
        {
            if (key != null && _tracked != null && _tracked.TryGetValue((typeof(TEntity), key), out var obj) && obj is TEntity typed)
            {
                entity = typed;
                return true;
            }
            entity = default!;
            return false;
        }

        /// <summary>Registers an entity reference against a unique key.</summary>
        public void Register<TEntity>(object key, TEntity entity) where TEntity : class
        {
            if (key != null && _tracked != null) _tracked[(typeof(TEntity), key)] = entity;
        }
    }
}
