using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using AutoMappic.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AutoMappic.Generator.Pipeline;

/// <summary>
///   Emits all generated C# source files for AutoMappic.
/// </summary>
internal static class SourceEmitter
{
    public static (string HintName, string Source) EmitMappingClass(MappingModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by AutoMappic – do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoMappic.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Generated static mapping from <see cref=\"{EscapeXml(model.SourceTypeFullName)}\" /> to <see cref=\"{EscapeXml(model.DestinationTypeFullName)}\" />.</summary>");
        sb.AppendLine($"internal static partial class {model.HintName}_Map");
        sb.AppendLine("{");

        var methodName = $"MapTo{model.DestinationTypeName}";
        var isAsync = model.IsAsync;

        // 1. Synchronous instance mapping
        sb.AppendLine($"    /// <summary>Maps a <see cref=\"{EscapeXml(model.SourceTypeFullName)}\" /> to a new <see cref=\"{EscapeXml(model.DestinationTypeFullName)}\" /> instance.</summary>");
        sb.AppendLine($"    public static {model.DestinationTypeFullName} {methodName}(this {model.SourceTypeFullName} source)");
        sb.AppendLine("    {");
        if (isAsync)
        {
            sb.AppendLine($"        return {methodName}Async(source).GetAwaiter().GetResult();");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine("        if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
            sb.AppendLine();
            if (model.TypeConverterFullName != null)
            {
                sb.AppendLine($"        return new {model.TypeConverterFullName}().Convert(source);");
            }
            else
            {
                EmitMappingBody(sb, model, false);
            }
            sb.AppendLine("    }");
        }

        // 2. Asynchronous instance mapping
        if (isAsync)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Asynchronously maps a <see cref=\"{EscapeXml(model.SourceTypeFullName)}\" /> to a new <see cref=\"{EscapeXml(model.DestinationTypeFullName)}\" /> instance.</summary>");
            sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<{model.DestinationTypeFullName}> {methodName}Async(this {model.SourceTypeFullName} source)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
            sb.AppendLine();
            EmitMappingBody(sb, model, true);
            sb.AppendLine("    }");
        }

        // 3. Synchronous in-place mapping
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Maps properties from <paramref name=\"source\" /> onto an existing <paramref name=\"destination\" /> instance.</summary>");
        sb.AppendLine($"    public static {model.DestinationTypeFullName} {methodName}(this {model.SourceTypeFullName} source, {model.DestinationTypeFullName} destination)");
        sb.AppendLine("    {");
        if (isAsync)
        {
            sb.AppendLine($"        return {methodName}Async(source, destination).GetAwaiter().GetResult();");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine("        if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
            sb.AppendLine("        if (destination is null) throw new global::System.ArgumentNullException(nameof(destination));");
            sb.AppendLine();
            EmitInPlaceBody(sb, model, false);
            sb.AppendLine("        return destination;");
            sb.AppendLine("    }");
        }

        // 4. Asynchronous in-place mapping
        if (isAsync)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Asynchronously maps properties from <paramref name=\"source\" /> onto an existing <paramref name=\"destination\" /> instance.</summary>");
            sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<{model.DestinationTypeFullName}> {methodName}Async(this {model.SourceTypeFullName} source, {model.DestinationTypeFullName} destination)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
            sb.AppendLine("        if (destination is null) throw new global::System.ArgumentNullException(nameof(destination));");
            sb.AppendLine();
            EmitInPlaceBody(sb, model, true);
            sb.AppendLine("        return destination;");
            sb.AppendLine("    }");
        }

        // 5. Collection Helpers
        var collectionHelpers = new List<PropertyMap>();
        CollectCollectionHelpers(model, collectionHelpers);
        foreach (var helper in collectionHelpers.GroupBy(h => h.DestinationProperty).Select(g => g.First()))
        {
            EmitCollectionHelper(sb, helper);
        }

        sb.AppendLine("}");
        return ($"{model.HintName}_Map.g.cs", sb.ToString());
    }

    private static void EmitMappingBody(StringBuilder sb, MappingModel model, bool isAsync)
    {
        var ctorArgExpressions = new List<string>();
        foreach (var arg in model.ConstructorArguments)
        {
            var expression = arg.SourceExpression;
            if (arg.IsCollection)
            {
                expression = $"MapCollection_{arg.DestinationProperty}_Ctor({arg.SourceExpression})";
            }
            ctorArgExpressions.Add(expression!);
        }

        var ctorCall = string.Join(", ", ctorArgExpressions);
        var initOnlyProps = model.Properties.Where(p => p.IsInitOnly && p.Kind != PropertyMapKind.Ignored).ToList();
        var otherProps = model.Properties.Where(p => !p.IsInitOnly && p.Kind != PropertyMapKind.Ignored).ToList();

        if (initOnlyProps.Count > 0)
        {
            sb.AppendLine($"        var result = new {model.DestinationTypeFullName}({ctorCall})");
            sb.AppendLine("        {");
            foreach (var prop in initOnlyProps)
            {
                var expression = prop.IsCollection && prop.NestedSourceTypeFullName != null ? $"MapCollection_{prop.DestinationProperty}({prop.SourceRawExpression ?? prop.SourceExpression})" : prop.SourceExpression;
                sb.AppendLine($"            {prop.DestinationProperty} = {expression}, // {prop.Kind}");
            }
            sb.AppendLine("        };");
        }
        else
        {
            sb.AppendLine($"        var result = new {model.DestinationTypeFullName}({ctorCall});");
        }

        // BeforeMap: emit sync first, then async (both run if both configured)
        if (isAsync)
        {
            if (!string.IsNullOrEmpty(model.BeforeMapBody)) sb.AppendLine($"        {model.BeforeMapBody}");
            if (!string.IsNullOrEmpty(model.BeforeMapAsyncBody)) sb.AppendLine($"        await (global::System.Threading.Tasks.Task.Run(async () => {{ {model.BeforeMapAsyncBody} }}));");
        }
        else if (!string.IsNullOrEmpty(model.BeforeMapBody))
        {
            sb.AppendLine($"        {model.BeforeMapBody}");
        }

        foreach (var prop in otherProps)
        {
            var expression = prop.IsCollection && prop.NestedSourceTypeFullName != null ? $"MapCollection_{prop.DestinationProperty}({prop.SourceRawExpression ?? prop.SourceExpression})" : prop.SourceExpression;
            if (prop.IsReadOnly)
            {
                if (prop.IsCollection)
                {
                    sb.AppendLine($"        var target{prop.DestinationProperty} = result.{prop.DestinationProperty};");
                    sb.AppendLine($"        if (target{prop.DestinationProperty} != null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            target{prop.DestinationProperty}.Clear();");
                    sb.AppendLine($"            foreach (var item in {expression}) target{prop.DestinationProperty}.Add(item);");
                    sb.AppendLine("        }");
                }
            }
            else
            {
                sb.AppendLine($"        result.{prop.DestinationProperty} = {expression}; // {prop.Kind}");
            }
        }

        // AfterMap: emit sync first, then async (both run if both configured)
        if (isAsync)
        {
            if (!string.IsNullOrEmpty(model.AfterMapBody)) sb.AppendLine($"        {model.AfterMapBody}");
            if (!string.IsNullOrEmpty(model.AfterMapAsyncBody)) sb.AppendLine($"        await (global::System.Threading.Tasks.Task.Run(async () => {{ {model.AfterMapAsyncBody} }}));");
        }
        else if (!string.IsNullOrEmpty(model.AfterMapBody))
        {
            sb.AppendLine($"        {model.AfterMapBody}");
        }
        sb.AppendLine("        return result;");
    }

    private static void EmitInPlaceBody(StringBuilder sb, MappingModel model, bool isAsync)
    {
        sb.AppendLine("        var result = destination;");
        // BeforeMap: emit sync first, then async (both run if both configured)
        if (isAsync)
        {
            if (!string.IsNullOrEmpty(model.BeforeMapBody)) sb.AppendLine($"        {model.BeforeMapBody}");
            if (!string.IsNullOrEmpty(model.BeforeMapAsyncBody)) sb.AppendLine($"        await (global::System.Threading.Tasks.Task.Run(async () => {{ {model.BeforeMapAsyncBody} }}));");
        }
        else if (!string.IsNullOrEmpty(model.BeforeMapBody))
        {
            sb.AppendLine($"        {model.BeforeMapBody}");
        }

        foreach (var prop in model.Properties)
        {
            if (prop.Kind == PropertyMapKind.Ignored || prop.IsInitOnly) continue;
            var expression = prop.IsCollection && prop.NestedSourceTypeFullName != null ? $"MapCollection_{prop.DestinationProperty}({prop.SourceRawExpression ?? prop.SourceExpression})" : prop.SourceExpression;
            if (prop.IsReadOnly)
            {
                if (prop.IsCollection)
                {
                    sb.AppendLine($"        var target{prop.DestinationProperty} = destination.{prop.DestinationProperty};");
                    sb.AppendLine($"        if (target{prop.DestinationProperty} != null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            target{prop.DestinationProperty}.Clear();");
                    sb.AppendLine($"            foreach (var item in {expression}) target{prop.DestinationProperty}.Add(item);");
                    sb.AppendLine("        }");
                }
            }
            else
            {
                sb.AppendLine($"        result.{prop.DestinationProperty} = {expression}; // {prop.Kind}");
            }
        }

        // AfterMap: emit sync first, then async (both run if both configured)
        if (isAsync)
        {
            if (!string.IsNullOrEmpty(model.AfterMapBody)) sb.AppendLine($"        {model.AfterMapBody}");
            if (!string.IsNullOrEmpty(model.AfterMapAsyncBody)) sb.AppendLine($"        await (global::System.Threading.Tasks.Task.Run(async () => {{ {model.AfterMapAsyncBody} }}));");
        }
        else if (!string.IsNullOrEmpty(model.AfterMapBody))
        {
            sb.AppendLine($"        {model.AfterMapBody}");
        }
    }

    private static void CollectCollectionHelpers(MappingModel model, List<PropertyMap> collectionHelpers)
    {
        foreach (var arg in model.ConstructorArguments.Where(a => a.IsCollection))
            collectionHelpers.Add(arg with { DestinationProperty = arg.DestinationProperty + "_Ctor" });

        foreach (var prop in model.Properties.Where(p => p.IsCollection && p.NestedSourceTypeFullName != null && p.Kind != PropertyMapKind.Ignored))
            collectionHelpers.Add(prop);
    }
    private static void EmitCollectionHelper(StringBuilder sb, PropertyMap helper)
    {
        var sItem = helper.NestedSourceTypeFullName!;
        var dItem = helper.NestedDestTypeFullName!;
        var dType = helper.IsArray ? $"{dItem}[]" : $"global::System.Collections.Generic.List<{dItem}>";
        var returnExpr = helper.IsArray ? "list.ToArray()" : "list";
        var innerLogic = helper.NestedExpression != null ? helper.NestedExpression.Replace("x", "element") : $"element.MapTo{dItem.Split('.').Last()}()";

        sb.AppendLine();
        sb.AppendLine($"    private static {dType} MapCollection_{helper.DestinationProperty}(global::System.Collections.Generic.IEnumerable<{sItem}>? source)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (source is null) return {(helper.IsArray ? $"global::System.Array.Empty<{dItem}>()" : $"new global::System.Collections.Generic.List<{dItem}>(0)")};");
        sb.AppendLine($"        var list = new global::System.Collections.Generic.List<{dItem}>();");
        sb.AppendLine("        foreach (var element in source)");
        sb.AppendLine("        {");
        sb.AppendLine($"            list.Add({innerLogic});");
        sb.AppendLine("        }");
        sb.AppendLine($"        return {returnExpr};");
        sb.AppendLine("    }");
    }

    public static (string HintName, string Source) EmitInterceptors(
        ImmutableArray<InterceptLocation> locations,
        IReadOnlyDictionary<string, MappingModel> mappingsByKey)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by AutoMappic – do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9113");
        sb.AppendLine("#pragma warning disable CS9270");
        sb.AppendLine();
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute(string filePath, int line, int column) : global::System.Attribute;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace AutoMappic.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class MapperInterceptors");
        sb.AppendLine("    {");

        foreach (var group in locations.GroupBy(l => new { l.MethodSignatureKey, l.DestinationTypeFullName, l.SourceTypeFullName, l.ParameterSourceTypeFullName, l.Kind, l.IsCollectionMapping, l.IsDestinationMapped, l.EffectiveSourceTypeFullName, l.EffectiveDestTypeFullName }))
        {
            var item = group.Key;
            var mappingKey = $"{Sanitise(item.SourceTypeFullName)}_To_{Sanitise(item.DestinationTypeFullName)}";
            var effectiveMappingKey = item.IsCollectionMapping
                ? $"{Sanitise(item.EffectiveSourceTypeFullName ?? item.SourceTypeFullName)}_To_{Sanitise(item.EffectiveDestTypeFullName ?? item.DestinationTypeFullName)}"
                : mappingKey;

            mappingsByKey.TryGetValue(effectiveMappingKey, out var model);
            if (item.Kind != InterceptKind.DataReaderMap && model == null) continue;

            var shimName = $"MapShim_{Sanitise($"{item.Kind}_{mappingKey}_{item.MethodSignatureKey}")}";
            foreach (var loc in group)
                sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation(@\"{EscapePath(loc.FilePath)}\", {loc.Line}, {loc.Column})]");

            if (item.Kind == InterceptKind.Map)
            {
                var isAsyncShim = item.MethodSignatureKey.StartsWith("MapAsync", StringComparison.Ordinal);
                var destName = model?.DestinationTypeName ?? item.DestinationTypeFullName.Split('.').Last();
                var sourceAccess = item.ParameterSourceTypeFullName == (model?.SourceTypeFullName ?? item.SourceTypeFullName) ? "source" : $"(({model?.SourceTypeFullName ?? item.SourceTypeFullName})source)";
                var isDestinationMapped = item.IsDestinationMapped;

                if (isAsyncShim)
                {
                    var method = model?.IsAsync == true ? $"MapTo{destName}Async" : $"MapTo{destName}";
                    var awaiter = model?.IsAsync == true ? "await " : "";
                    var resultTask = "";
                    var resultEnd = "";
                    var configure = model?.IsAsync == true ? ".ConfigureAwait(false)" : "";

                    if (isDestinationMapped)
                    {
                        sb.AppendLine($"        public static async global::System.Threading.Tasks.Task<{item.DestinationTypeFullName}> {shimName}(this global::AutoMappic.IMapper mapper, {item.ParameterSourceTypeFullName} source, {item.DestinationTypeFullName} destination)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
                        sb.AppendLine($"            return {resultTask}{awaiter}{sourceAccess}.{method}(destination){configure}{resultEnd};");
                        sb.AppendLine("        }");
                    }
                    else
                    {
                        sb.AppendLine($"        public static async global::System.Threading.Tasks.Task<{item.DestinationTypeFullName}> {shimName}(this global::AutoMappic.IMapper mapper, {item.ParameterSourceTypeFullName} source)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
                        sb.AppendLine($"            return {resultTask}{awaiter}{sourceAccess}.{method}(){configure}{resultEnd};");
                        sb.AppendLine("        }");
                    }
                }
                else
                {
                    if (isDestinationMapped)
                    {
                        sb.AppendLine($"        public static {item.DestinationTypeFullName} {shimName}(this global::AutoMappic.IMapper mapper, {item.ParameterSourceTypeFullName} source, {item.DestinationTypeFullName} destination)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
                        sb.AppendLine($"            return {sourceAccess}.MapTo{destName}(destination);");
                        sb.AppendLine("        }");
                    }
                    else
                    {
                        sb.AppendLine($"        public static {item.DestinationTypeFullName} {shimName}(this global::AutoMappic.IMapper mapper, {item.ParameterSourceTypeFullName} source)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
                        sb.AppendLine($"            return {sourceAccess}.MapTo{destName}();");
                        sb.AppendLine("        }");
                    }
                }
            }
            // ... (ProjectTo and DataReaderMap omitted for brevity in this cleanup, but they should remain)
            else if (item.Kind == InterceptKind.ProjectTo)
            {
                var destName = model?.DestinationTypeName ?? item.DestinationTypeFullName.Split('.').Last();
                sb.AppendLine($"        public static global::System.Linq.IQueryable<{item.DestinationTypeFullName}> {shimName}(this global::System.Linq.IQueryable<{item.SourceTypeFullName}> source)");
                sb.AppendLine($"        {{ return source.Select(x => x.MapTo{destName}()); }}");
            }
            else if (item.Kind == InterceptKind.DataReaderMap)
            {
                var destName = model?.DestinationTypeName ?? item.DestinationTypeFullName.Split('.').Last();
                sb.AppendLine($"        public static global::System.Collections.Generic.IEnumerable<{item.DestinationTypeFullName}> {shimName}(this global::System.Data.IDataReader reader)");
                sb.AppendLine($"        {{ while (reader.Read()) yield return reader.MapTo{destName}(); }}");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return ("AutoMappic.Interceptors.g.cs", sb.ToString());
    }

    public static (string HintName, string Source) EmitRegistration(string assemblyName, ImmutableArray<string?> profiles, ImmutableArray<MappingModel> localMappings, ImmutableArray<string> referencedAssemblies, bool isEntryPoint)
    {
        var sb = new StringBuilder();
        var sanitized = Sanitise(assemblyName);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        foreach (var m in localMappings) sb.AppendLine($"[assembly: global::AutoMappic.MappingDiscoveryAttribute(typeof(global::{m.SourceTypeFullName}), typeof(global::{m.DestinationTypeFullName}))]");
        var pList = profiles.IsDefaultOrEmpty ? "" : string.Join(", ", profiles.Distinct().Where(p => p != null).Select(p => $"typeof(global::{p})"));
        sb.AppendLine($"[assembly: global::AutoMappic.HasAutoMappicProfilesAttribute({pList})]");
        sb.AppendLine();
        sb.AppendLine("namespace AutoMappic.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    internal static class {sanitized}_Registration");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void AddProfiles(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        foreach (var p in profiles.Distinct().Where(x => x != null)) sb.AppendLine($"            services.AddSingleton<global::AutoMappic.Profile, global::{p}>();");
        foreach (var r in referencedAssemblies.Distinct()) sb.AppendLine($"            global::AutoMappic.Generated.{Sanitise(r)}_Registration.AddProfiles(services);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class AutoMappic_{sanitized}_Extensions");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static IServiceCollection AddAutoMappicFrom{sanitized}(this IServiceCollection services) {{ global::AutoMappic.Generated.{sanitized}_Registration.AddProfiles(services); return services.AddSingleton<global::AutoMappic.IMapper>(sp => new global::AutoMappic.MapperConfiguration(cfg => {{ foreach(var p in sp.GetServices<global::AutoMappic.Profile>()) cfg.AddProfile(p); }}).CreateMapper()); }}");
        if (isEntryPoint) sb.AppendLine("        public static IServiceCollection AddAutoMappic(this IServiceCollection services) => AddAutoMappicFrom" + sanitized + "(services);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return ("AutoMappic.Registration.g.cs", sb.ToString());
    }

    private static string EscapeXml(string value) => value.Replace("<", "&lt;").Replace(">", "&gt;");
    private static string EscapePath(string path) => path.Replace("\"", "\\\"");
    private static string Sanitise(string name)
    {
        var res = new StringBuilder();
        foreach (var c in name ?? "Default") if (char.IsLetterOrDigit(c)) res.Append(c); else res.Append('_');
        return res.ToString();
    }
}
