using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using AutoMappic.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AutoMappic.Generator.Pipeline;

/// <summary>
///   Emits all generated C# source files for AutoMappic.
/// </summary>
/// <remarks>
///   <para>Two kinds of source files are produced:</para>
///   <list type="number">
///     <item>
///       <description>
///         A static extension class per mapping pair, e.g.
///         <c>Order_To_OrderDto_Map.g.cs</c>, containing a
///         <c>MapToOrderDto(this Order source)</c> static method with direct property
///         assignments.  No reflection.  Fully debuggable.
///       </description>
///     </item>
///     <item>
///       <description>
///         A single <c>AutoMappic.Interceptors.g.cs</c> file containing one static method per
///         intercepted call site, each decorated with an <c>[InterceptsLocation]</c>
///         attribute that redirects the compiler to our generated static method.
///       </description>
///     </item>
///   </list>
/// </remarks>
internal static class SourceEmitter
{
    /// <summary>Emits the static mapping class for a single <see cref="MappingModel" />.</summary>
    public static (string HintName, string Source) EmitMappingClass(MappingModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by AutoMappic – do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoMappic.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Generated static mapping from <see cref=\"{EscapeXml(model.SourceTypeFullName)}\" /> to <see cref=\"{EscapeXml(model.DestinationTypeFullName)}\" />.</summary>");
        sb.AppendLine($"internal static partial class {model.HintName}_Map");
        sb.AppendLine("{");

        var methodName = $"MapTo{model.DestinationTypeName}";

        sb.AppendLine($"    /// <summary>Maps a <see cref=\"{EscapeXml(model.SourceTypeFullName)}\" /> to a new <see cref=\"{EscapeXml(model.DestinationTypeFullName)}\" /> instance.</summary>");
        sb.AppendLine($"    public static {model.DestinationTypeFullName} {methodName}(this {model.SourceTypeFullName} source)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
        sb.AppendLine();
        sb.AppendLine($"        return new {model.DestinationTypeFullName}");
        sb.AppendLine("        {");

        foreach (var prop in model.Properties)
        {
            if (prop.Kind == PropertyMapKind.Ignored) continue;

            sb.AppendLine($"            {prop.DestinationProperty} = {prop.SourceExpression}, // {prop.Kind}");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");

        // Also emit an in-place overwrite overload.
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Maps properties from <paramref name=\"source\" /> onto an existing <paramref name=\"destination\" /> instance.</summary>");
        sb.AppendLine($"    public static {model.DestinationTypeFullName} {methodName}(this {model.SourceTypeFullName} source, {model.DestinationTypeFullName} destination)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (source is null) throw new global::System.ArgumentNullException(nameof(source));");
        sb.AppendLine("        if (destination is null) throw new global::System.ArgumentNullException(nameof(destination));");
        sb.AppendLine();

        foreach (var prop in model.Properties)
        {
            if (prop.Kind == PropertyMapKind.Ignored || prop.IsInitOnly) continue;
            sb.AppendLine($"        destination.{prop.DestinationProperty} = {prop.SourceExpression}; // {prop.Kind}");
        }

        sb.AppendLine("        return destination;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return ($"{model.HintName}_Map.g.cs", sb.ToString());
    }

    /// <summary>
    ///   Emits the single <c>AutoMappic.Interceptors.g.cs</c> file containing all
    ///   <c>[InterceptsLocation]</c> shims plus the required attribute definition.
    /// </summary>
    public static (string HintName, string Source) EmitInterceptors(
        ImmutableArray<InterceptLocation> locations,
        IReadOnlyDictionary<string, MappingModel> mappingsByKey)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by AutoMappic – do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9113 // Primary constructor parameter is unread");
        sb.AppendLine("#pragma warning disable CS9270 // InterceptsLocationAttribute is deprecated");
        sb.AppendLine();

        // The InterceptsLocationAttribute must be defined in the compilation if the SDK
        // version doesn't ship one already.  We guard with a conditional compilation.
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute(string filePath, int line, int column) : global::System.Attribute;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace AutoMappic.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class MapperInterceptors");
        sb.AppendLine("    {");

        // Group locations by their MethodSignatureKey and Kind to avoid duplicate method bodies
        var groupedLocations = locations.GroupBy(l => new { l.MethodSignatureKey, l.DestinationTypeFullName, l.SourceTypeFullName, l.ParameterSourceTypeFullName, l.Kind });

        foreach (var group in groupedLocations)
        {
            var key = group.Key;
            var mappingKey = $"{key.SourceTypeFullName}_To_{key.DestinationTypeFullName}";
            mappingsByKey.TryGetValue(mappingKey, out var model);

            // DataReaderMap does not need a pre-existing profile model.
            if (key.Kind != InterceptKind.DataReaderMap && model == null) continue;

            var methodSuffix = Sanitise($"{key.Kind}_{mappingKey}");
            var shimName = $"MapShim_{methodSuffix}";

            foreach (var location in group)
            {
                sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation(@\"{EscapePath(location.FilePath)}\", {location.Line}, {location.Column})]");
            }

            if (key.Kind == InterceptKind.Map)
            {
                var destMappingMethod = $"MapTo{model!.DestinationTypeName}";
                var isAsync = key.MethodSignatureKey.StartsWith("MapAsync", System.StringComparison.Ordinal);
                var sourceAccess = key.ParameterSourceTypeFullName == model.SourceTypeFullName
                    ? "source"
                    : $"(({model.SourceTypeFullName})source)";

                if (isAsync)
                {
                    sb.AppendLine($"        public static global::System.Threading.Tasks.Task<{model.DestinationTypeFullName}> {shimName}(this global::AutoMappic.IMapper mapper, {key.ParameterSourceTypeFullName} source)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return global::System.Threading.Tasks.Task.FromResult({sourceAccess}.{destMappingMethod}());");
                    sb.AppendLine("        }");
                }
                else
                {
                    sb.AppendLine($"        public static {model.DestinationTypeFullName} {shimName}(this global::AutoMappic.IMapper mapper, {key.ParameterSourceTypeFullName} source)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return {sourceAccess}.{destMappingMethod}();");
                    sb.AppendLine("        }");
                }
            }
            else if (key.Kind == InterceptKind.ProjectTo)
            {
                var destMappingMethod = $"MapTo{model!.DestinationTypeName}";
                sb.AppendLine($"        public static global::System.Linq.IQueryable<{model.DestinationTypeFullName}> {shimName}(this global::System.Linq.IQueryable source)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return global::System.Linq.Queryable.Select((global::System.Linq.IQueryable<{model.SourceTypeFullName}>)source, src => new {model.DestinationTypeFullName}");
                sb.AppendLine("            {");
                foreach (var prop in model.Properties)
                {
                    if (prop.Kind == PropertyMapKind.Ignored || prop.IsInitOnly) continue;
                    // replace 'source.' with 'src.' for the projection expression
                    var expr = prop.SourceExpression?.Replace("source.", "src.");
                    sb.AppendLine($"                {prop.DestinationProperty} = {expr},");
                }
                sb.AppendLine("            });");
                sb.AppendLine("        }");
            }
            else if (key.Kind == InterceptKind.DataReaderMap)
            {
                sb.AppendLine($"        public static global::System.Collections.Generic.IEnumerable<{key.DestinationTypeFullName}> {shimName}(this global::System.Data.IDataReader reader)");
                sb.AppendLine("        {");
                sb.AppendLine("            while (reader.Read())");
                sb.AppendLine("            {");
                sb.AppendLine($"                yield return new {key.DestinationTypeFullName}");
                sb.AppendLine("                {");

                if (model != null)
                {
                    foreach (var prop in model.Properties)
                    {
                        if (prop.Kind == PropertyMapKind.Ignored || prop.IsInitOnly) continue;

                        var destName = prop.DestinationProperty;
                        var sourceExpr = prop.SourceExpression?.Replace("source.", "") ?? "default";
                        sb.AppendLine($"                    {destName} = reader.GetValue(reader.GetOrdinal(\"{destName}\")) is global::System.DBNull ? default : ({sourceExpr})reader.GetValue(reader.GetOrdinal(\"{destName}\")),");
                    }
                }

                sb.AppendLine("                };");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return ("AutoMappic.Interceptors.g.cs", sb.ToString());
    }

    /// <summary>
    ///   Emits a static extension method for IServiceCollection that registers
    ///   all discovered Profile classes without using reflection, supporting
    ///   cross-project discovery via static chaining.
    /// </summary>
    public static (string HintName, string Source) EmitRegistration(
        string assemblyName,
        ImmutableArray<string?> profiles,
        ImmutableArray<MappingModel> localMappings,
        ImmutableArray<string> referencedAssemblies,
        bool isEntryPoint)
    {
        var sb = new StringBuilder();
        var sanitizedAssemblyName = Sanitise(assemblyName);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by AutoMappic – do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using AutoMappic;");
        sb.AppendLine();

        // 1. Breadcrumbs: Mark this assembly as having AutoMappic profiles and mappings.
        // We use typed constructor arguments for robust discovery via assembly metadata.
        foreach (var mapping in localMappings)
        {
            sb.AppendLine($"[assembly: AutoMappic.Generated.MappingDiscoveryAttribute(typeof(global::{mapping.SourceTypeFullName}), typeof(global::{mapping.DestinationTypeFullName}))]");
        }

        var profileTypeList = profiles.IsDefaultOrEmpty ? "" : string.Join(", ", profiles.Distinct().Where(p => p != null).Select(p => $"typeof(global::{p})"));
        sb.AppendLine($"[assembly: AutoMappic.Generated.HasAutoMappicProfilesAttribute({profileTypeList})]");
        sb.AppendLine();

        sb.AppendLine("namespace AutoMappic.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Internal marker attribute to enable cross-project mapping discovery.</summary>");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]");
        sb.AppendLine("    internal sealed class MappingDiscoveryAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public MappingDiscoveryAttribute(global::System.Type source, global::System.Type destination) { }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Internal marker attribute to enable cross-project profile discovery.</summary>");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]");
        sb.AppendLine("    internal sealed class HasAutoMappicProfilesAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public HasAutoMappicProfilesAttribute(params global::System.Type[] profiles) { }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Project-specific registration for {assemblyName}.</summary>");
        sb.AppendLine($"    internal static class {sanitizedAssemblyName}_Registration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers profiles from this assembly and all referenced projects.</summary>");
        sb.AppendLine("        public static void AddProfiles(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        // Local profiles
        if (!profiles.IsDefaultOrEmpty)
        {
            sb.AppendLine("            // Local Profiles found in this project");
            foreach (var profile in profiles.Distinct())
            {
                if (profile == null) continue;
                sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::AutoMappic.Profile, global::{profile}>(services);");
            }
        }

        // Referenced projects - chain their registrations
        if (!referencedAssemblies.IsDefaultOrEmpty)
        {
            sb.AppendLine();
            sb.AppendLine("            // Discover and chain registrations from referenced assemblies");
            foreach (var reference in referencedAssemblies.Distinct())
            {
                var sanitizedRef = Sanitise(reference);
                sb.AppendLine($"            global::AutoMappic.Generated.{sanitizedRef}_Registration.AddProfiles(services);");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // 2. The Main Entry Point: generate the public extension method.
        // We always generate this, but we use a unique name per assembly to avoid collisions
        // while also providing the standard 'AddAutoMappic' if we're the entry point.
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Generated dependency injection registration for AutoMappic in {assemblyName}.</summary>");
        sb.AppendLine($"    public static class AutoMappic_{sanitizedAssemblyName}_Extensions");
        sb.AppendLine("    {");

        // Always provide a project-specific one
        sb.AppendLine($"        /// <summary>Adds AutoMappic profiles discovered in {assemblyName} and its references.</summary>");
        sb.AppendLine($"        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoMappicFrom{sanitizedAssemblyName}(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine($"            global::AutoMappic.Generated.{sanitizedAssemblyName}_Registration.AddProfiles(services);");
        sb.AppendLine("            return AddAutoMappicCore(services);");
        sb.AppendLine("        }");

        // If it's the entry point (or we just want a standard name), provide the parameterless AddAutoMappic
        if (isEntryPoint)
        {
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Root AutoMappic registration for the application.</summary>");
            sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoMappic(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return AddAutoMappicFrom{sanitizedAssemblyName}(services);");
            sb.AppendLine("        }");
        }

        sb.AppendLine();
        sb.AppendLine("        private static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoMappicCore(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Ensure the mapper engine is registered as a singleton.");
        sb.AppendLine("            if (!global::System.Linq.Enumerable.Any(services, s => s.ServiceType == typeof(global::AutoMappic.IMapper)))");
        sb.AppendLine("            {");
        sb.AppendLine($"                global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::AutoMappic.IMapper>(services, sp => ");
        sb.AppendLine("                {");
        sb.AppendLine("                    var profileList = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::AutoMappic.Profile>(sp);");
        sb.AppendLine("                    var config = new global::AutoMappic.MapperConfiguration(cfg => ");
        sb.AppendLine("                    {");
        sb.AppendLine("                        foreach (var p in profileList) cfg.AddProfile(p);");
        sb.AppendLine("                    });");
        sb.AppendLine("                    return config.CreateMapper();");
        sb.AppendLine("                });");
        sb.AppendLine("            }");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return ("AutoMappic.Registration.g.cs", sb.ToString());
    }

    private static string EscapeXml(string value) =>
        value.Replace("<", "&lt;").Replace(">", "&gt;");

    private static string EscapePath(string path) =>
        path.Replace("\"", "\\\"");

    private static string Sanitise(string name) =>
        name.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');
}
